MONGO_URL = 'localhost'
# MONGO_DB = 'campany_informaiton'
# MONGO_DB = 'informaiton'
# MONGO_DB = 'informaiton2'
MONGO_DB = 'informaiton3'
MONGO_TABLE = 'campany_informaiton'
GROUP_START=0
GROUP_END=50
start = 1
end = 200000
keywordlist=['上海市浦东新区','上海市闵行','上海市宝山','上海市嘉定','上海市宝山','上海嘉定区','上海闵行区','上海松江','上海青浦','上海奉贤','上海金山']
#keyword ='上海市闵行区'
